---
title: "tidyverse packages demo"
output: html_notebook
---

**5 key dplyr verbs**
1. filter: pick observation by their values
2. arrange: reorder rows
3. select: pick variables by their names
4. mutate: create new variables with functions of existing variables
5. summarize: collapse many values down to a single summary

**Examples**

```{r, filter}
# load necessary packages
library(magrittr)
library(tidyverse)
  
# print first observations of dataframe
head(mtcars)

# filter cars with good MPG
filter(mtcars, mpg > 20)
mtcars %>% filter(mpg > 20)

# are these equivalent to the same thing?
filter(mtcars, mpg > 20) == mtcars %>% filter(mpg > 20)
identical(filter(mtcars, mpg > 20),
          mtcars %>% filter(mpg > 20))

# which filter function are we using?
?filter()
?stats::filter()


```

```{r, arrange function}
# What do you think these commands will do?
mtcars %>% arrange(mpg)
mtcars %>% arrange(mpg, desc(hp))
```

My favorite function for creating my own data frame: tribble()
```{r, create your own data}
library(tibble)

# print a dataframe to console
tribble(
~colA, ~colB,
   "a",   1,
   "b",   2,
   "c",   3
)

# save dataframe as variable
df <- tribble(
  ~food, ~score, ~initials,
  "cucumber", 8, "HD",
  "apple", 8, "HD",
  "kale", 10, "HD",
  "dark chocolate", 7, "HD",
  "donuts", 0, "HD"
  # add more scores here
  
)

# what function would you use to print or view the table?

```

```{r, select}
# drop the initials column
df.mod <- df %>% select(food, score)
df.mod <- df %>% select(-initials)

```


```{r, mutate}

# create a new column
df.mod <- df %>%
  select(food,score) %>%
  mutate(new.score = score -1)

# create a more useful column
df.mod <- df %>%
  select(food,score) %>%
  mutate(new.score = cut(score, breaks = c(-Inf,5,6,7,9,10, Inf), labels = c("F", "D", "C", "B", "A", "A+")))

print(df.mod)


```


```{r, summarize}

df %>% summarize(mean.score = mean(score))
df %>% 
  group_by(initials) %>%
  summarize(mean.score = mean(score))
```

