---
title: "World Happiness Report"
params:
  region:
    label: "Region:"
    input: select
    value: "america"
    choices: ["latin america", "africa", "uk", "oceania", "asia"]
  top.countries: 100
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Happiness Score by Region  
Regions:  ”eurasia”,”africa”,”latin america”,”uk”,”oceania”,”asia"  
Article on [rworldmap](http://colorado.rstudio.com/rstudio/s/ce6086fe78a415709b3b4/files/R/x86_64-pc-linux-gnu-library/3.4/rworldmap/doc/rworldmap.pdf) package.

```{r, message = FALSE, include = FALSE}
# environment setup
library(tidyverse)
library(rworldmap)
library(rlang)

# load data
df <- read_csv("data/2017.csv")
```

```{r, message=FALSE, warning=FALSE, include=FALSE}

# join happiness date to map
map <- joinCountryData2Map( df
,joinCode = "NAME"
,nameJoinColumn = "Country"
,verbose = TRUE)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# pick color scheme

colourPalette <- RColorBrewer::brewer.pal(7,'YlGn')
                                          
# plot map
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
map.params <- mapCountryData( map,
                  nameColumnToPlot="Happiness.Score",
                  #zoom
                  mapRegion = params$region,
                  oceanCol="lightblue",
                  missingCountryCol="white",
                  colourPalette = colourPalette,
                  addLegend=FALSE)
do.call( addMapLegend, c(map.params, legendWidth=0.5, legendMar = 2))
```

## Happiness by country   
**Is happiness associated with a high GDP?**

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# filter data
df.sub <- df %>%
  top_n(-params$top.countries, wt = Happiness.Rank)

ggplot(df.sub, aes(Economy..GDP.per.Capita., Happiness.Score, label = Country)) +
  geom_label() +
  labs(title = paste("Top", params$top.countries, "happiest countries"))
```




