---
title: "World Capitals"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

# World Stats 

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(readr)
library(dplyr)
library(leaflet)
library(corrplot)
library(plotly)

```


```{r load-data, include=FALSE}
# load capital data
file.info("World capitals - Sheet1.csv") # check file size
df <- read_csv("World capitals - Sheet1.csv")

# load happiness data
df.happiness <- read_csv("2017.csv")

```


```{r data-wrangle, include=FALSE}
# clean up data
df <- df %>%
        mutate_at(vars(Latitude, Longitude), # * _at affects variables selected with a character vector or vars()
            funs(as.numeric(gsub("[NE]$", "", gsub("^(.*)[WS]$", "-\\1", .)))))

```

## Sidebar {.sidebar} 

```{r input-boxes}
selectInput(inputId = "Country", label = "Country", choices = df$Country, multiple = TRUE, selected = df$Country[1:2])

```

Column {data-width=650} 
-----------------------------------------------------------------------

### Leaflet Map 

```{r leaflet-map}

# define map markers
icons <- makeAwesomeIcon(
           icon= 'star-empty', 
           markerColor = 'green',
           iconColor = 'white', 
           library = 'glyphicon'
          )

# render plot
renderLeaflet({
  
  # filter based on input
  selectedData <- df %>% filter(Country %in% input$Country)
  
  # print map
  leaflet(selectedData) %>% # creates container
  addTiles() %>% # adds default tile from open street maps
  addAwesomeMarkers(lng = ~Longitude, lat = ~Latitude, popup = paste(selectedData$Country,", ", selectedData$Capital, sep = ""), icon = icons)
})





```

## Column {data-width=350} 


### Gauges 

```{r}
# Add gauges
score <- round(mean(df.happiness$Happiness.Score),1)
life <- round(mean(df.happiness$Health..Life.Expectancy.),1)


# Gauge
gauge(score, min = 0, max =10, label = "Happiness Score", gaugeSectors(
  success = c(8, 10), warning = c(5, 7), danger = c(0, 4)
))

gauge(life, min = 0, max =.9, label = "Life Expectancy", gaugeSectors(
  success = c(.6, .9), warning = c(.4, .5), danger = c(.0, .3)
))


```

### Correlation 

```{r}
M <- cor(df.happiness[ ,-1])
corrplot(M, method="circle", tl.cex = 0.6)

```


# USA Population {data-icon="fa-map"} 

```{r}
# example plotly graph
# code source: https://plot.ly/r/bubble-maps/

df2 <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_us_cities.csv')

df2$q <- with(df, cut(df2$pop, quantile(df2$pop)))
levels(df2$q) <- paste(c("1st", "2nd", "3rd", "4th", "5th"), "Quantile")
df2$q <- as.ordered(df2$q)

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showland = TRUE,
  landcolor = toRGB("gray85"),
  subunitwidth = 1,
  countrywidth = 1,
  subunitcolor = toRGB("white"),
  countrycolor = toRGB("white")
)

p <- plot_geo(df2, locationmode = 'USA-states', sizes = c(1, 250)) %>%
  add_markers(
    x = ~lon, y = ~lat, size = ~pop, color = ~q, hoverinfo = "text",
    text = ~paste(df2$name, "<br />", df2$pop/1e6, " million")
  ) %>%
  layout(title = '2014 US city populations<br>(Click legend to toggle)', geo = g)

# print plot
p


```

# USA Population {data-icon="fa-car"} 